version: '3.8'

services:
  retriever:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - chromadb
    environment:
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--log-level", "debug"]

  answer_generation:
    build:
      context: .
      dockerfile: ./answer_generation/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY
      - RETRIEVER_URL=http://retriever:8001
    depends_on:
      - retriever
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--log-level", "debug"]

  tg_bot:
    build:
      context: .
      dockerfile: ./tg_bot/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    environment:
      - ANSWERING_HOST=http://answer_generation:8002
      - RETRIEVER_URL=http://retriever:8001
    depends_on:
      - answer_generation
    command: ["python", "main.py"]

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_PATH=/data
      - POSTHOG_DISABLED=true
    volumes:
      - ./chromadb_data:/data
